---
- name: Install utils
  hosts: all
  gather_facts: true

  tasks:
    - name: create vagrant group
      ansible.builtin.group:
        name: vagrant
        state: present

    - name: Add the user 'vagrant'
      ansible.builtin.user:
        name: vagrant
        comment: Vaga
        group: vagrant
        shell: /bin/bash

    - name: install packages
      ansible.builtin.yum:
        name:
          - bind
          - bind-utils
          - ntp
        state: latest 

    - name: copy transferkey to all servers and the client
      ansible.builtin.template:
        src: named.zonetransfer.key
        dest: /etc/named.zonetransfer.key
        owner: root
        group: named
        mode: '0644'

- name: conf ms01
  hosts: ns01
  tasks:
    - name: copy named.conf
      ansible.builtin.template: 
        src: master-named.conf 
        dest: /etc/named.conf 
        owner: root 
        group: named 
        mode: 0640

    - name: copy zones
      ansible.builtin.copy:
        src: '{{ item }}'
        dest: /etc/named/ 
        owner: root 
        group: named 
        mode: 0660
      with_fileglob:
        - named.d*
        - named.newdns.lab


    - name: copy resolv.conf to the servers
      ansible.builtin.template:
        src: servers-resolv.conf.j2
        dest: /etc/resolv.conf 
        owner: root 
        group: root 
        mode: 0644

    - name: set /etc/bind/named permissions
      ansible.builtin.file:  
        path: /etc/named/ 
        owner: root
        group: named
        mode: 0670

    - name: ensure named is running and enabled
      ansible.builtin.systemd_service: 
        name: named
        state: restarted
        enabled: yes

- name: conf ms02
  hosts: ns02
  tasks:
    - name: copy named.conf
      ansible.builtin.template:
        src: slave-named.conf
        dest: /etc/named.conf
        owner: root
        group: named
        mode: 0640

    - name: copy resolv.conf to the servers
      ansible.builtin.template:
        src: servers-resolv.conf.j2
        dest: /etc/resolv.conf
        owner: root
        group: root
        mode: 0644

    - name: set /etc/bind/named permissions
      ansible.builtin.file: 
        path: /etc/named
        owner: root 
        group: named
        mode: 0670

    - name: ensure named is running and enabled
      ansible.builtin.systemd_service:
        name: named 
        state: restarted
        enabled: yes

- name: conf clients
  hosts: clients
  tasks:
    - name: copy resolv.conf to the client
      ansible.builtin.template:
        src: client-resolv.conf
        dest: /etc/resolv.conf
        owner: root 
        group: root 
        mode: 0644

    - name: copy rndc conf file
      ansible.builtin.template:
        src: rndc.conf
        dest: /home/vagrant/rndc.conf
        owner: vagrant
        group: vagrant
        mode: 0644
        
    - name: copy motd to the client
      ansible.builtin.template:
        src: client-motd
        dest: /etc/motd
        owner: root
        group: root
        mode: 0644